[dependencies]

[package]
  cjc-version = "0.56.4"
  compile-option = ""
  description = "适用于仓颉的 glob 库"
  link-option = ""
  name = "glob_cj"
  output-type = "static"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
